# Generated by Django 5.2.8 on 2025-11-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to='audio/originals/')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='audio/processed/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
